---
apiVersion: v1
kind: PersistentVolume

metadata:
  namespace: minio
  name: pv-minio
  labels:
    app: minio
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/kube/minio"
    type: DirectoryOrCreate
  claimRef:
    namespace: minio
    name: pvc-minio
