---
apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  namespace: minio
  name: pvc-minio
  labels:
    app: minio

spec:
# storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
