apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 08-jenkins
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins
  source:
    repoURL: 'https://github.com/Hallikas/dev-system.git'
    path: 08-jenkins
    targetRevision: HEAD
  project: system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
