apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 10-atlassian
  namespace: argocd
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: atlassian
  source:
    repoURL: 'https://github.com/Hallikas/dev-system.git'
    path: 10-atlassian
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
