apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: default
spec:
  encryptedData:
    foo: AgADgVwdJ1JpHtxPfUSXyC+WtA5rwsIVBRa8wYj7BVJAIVFOBXUIIgmoYwGWy4VmH2Rrqy9jCDC7b8bV0YBP9f/N2j9w8a3URk22SjYVBmrs/U71dM6cSylUMF4wmmCxlUGmlBoGBk+bw6XzXvejak7lfxdsKJ+WjA+eaotaIPvh0X6v9lQFbpJxqz7ZgnO4Jrzo7wfCi5Xv4ZC/hU3ZPMCkXPUjaqPnuIzMWat6o8t0LiUnPW3ekHipCwo1jZOewkkyFUhLhY+hnbmTvT2AZ5ffW2njtNzxUdRLLLv2mgb8RWTw+gUH+/PvkRAs+FuVIkP9WsgwrKrp+Iel5iv0FEy/2IZJ2ghP6ykuExL8C3iO4g9RT3HctQsFAfhhP17jJUeId1UAC/w4iGJ499zw2KJAM0xHSh+pSh1/UJlUsO56PU4/TxLZ13G4DqJZU2ziqB/nXYO+9l/kQgV1A1cGZX677w1mHNMprAoC8yymD0FQ+Nr46nBvTt9GGawqze9oiwrc+0rPcAHJlSWgZ9Lndpol7xW0Ch6QclIhDo6ruK//Rm5zKa/EMDYZQouPhn4Er00SgEzyZSjMktYuB3/9e4x6WCM7A+rkae69kwLP2mPyt7rHnKkLb4iReuFi5lDEfAG0WnUFE6YG1R03Epsv0OK9VH8q+lH5VKV54Di/9BYR34pAbj9Y2sdjDypcheWosQIUaRI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: default

