apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab-postgresql
  labels:
    app: postgresql
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/kube/gitlab/postgresql"
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: data-gitlab-postgresql-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab-redis
  labels:
    app: gitlab-redis
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 6Gi
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/kube/gitlab/redis"
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: redis-data-gitlab-redis-master-0
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-gitlab-gitaly
  labels:
    app: gitlab
    type: local
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  storageClassName: microk8s-hostpath
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/data/kube/gitlab/gitaly"
    type: DirectoryOrCreate
  claimRef:
    namespace: gitlab
    name: repo-data-gitlab-gitaly-0
### Not in use, yet
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: gitlab-prometheus-server
#  labels:
#    app: prometheus
#    type: local
#spec:
#  accessModes:
#  - ReadWriteOnce
#  capacity:
#    storage: 10Gi
#  storageClassName: microk8s-hostpath
#  persistentVolumeReclaimPolicy: Retain
#  hostPath:
#    path: "/data/kube/gitlab/prometheus"
#    type: DirectoryOrCreate
#  claimRef:
#    namespace: gitlab
#    name: gitlab-prometheus-server
#