apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-gitlab-postgresql-0
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: pv-gitlab-postgresql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-gitlab-redis-master-0
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 6Gi
  volumeName: pv-gitlab-redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repo-data-gitlab-gitaly-0
  namespace: gitlab
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: pv-gitlab-gitaly
